version: '3.8'

services:
  usuarios-service:
    image: renanafs/usuarios-service:latest  # imagem jรก publicada no Docker Hub
    container_name: usuarios-service
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
