version: '3.8'

services:
  usuarios-service:
    build: .
    container_name: usuarios-service
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development